language: ruby
script: "bundle exec rspec spec"
rvm:
  - "2.2.4"
  - "2.3.1"
  - "jruby-9000"
  - "jruby-head"
  - "rbx"
  - "ruby-head"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: jruby-9000
    - rvm: jruby-head
env:
  global:
    - CC_TEST_REPORTER_ID=cdae638d374998cf1a2e011f6b93eef5693815d816c9d830932f94f6a1593457
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
